<a href="https://colab.research.google.com/github/marigisee/Deep-Learning-UNLP/blob/main/practica0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Práctica 0


##Jupyter Notebooks y Google Colab

#### Ejercicio 2
Experimente la ejecución de varios comandos del sistema operativo a través de celdas de código.

In [ ]:
#archivos de la carpeta actual
!ls
#!pip
#versión de python instalada en la computadora virtual
!python --version
#versión instalada del paquete numpy
!pip show numpy
#comando para crear carpeta
!mkdir nuevaCarpeta
!mkdir nuevaCarpeta2
#comando para eliminar una carpeta
!rm -r nuevaCarpeta

#### Ejercicio 3


Suba un pequeño archivo de texto a Drive (NO a Colab) y ábralo desde una celda de código Colab

In [ ]:
ruta_arch = "drive/MyDrive/textfileDrive.txt" # ruta y nombre a archivo a LEER desde su drive
f = open(ruta_arch, 'r') # abre archivo para leer
print(f.readlines()) # imprime contenido en pantalla
f.close() # cierra archivo

['Hola! Esto es un archivo de texto subido a Google Drive! ']


Genere el siguiente archivo 'fileGenerated.txt' y guárdelo en su carpeta Drive, comprobando que efectivamente se ha creado
con el contenido esperado

In [ ]:
**ruta_arch** = 'drive/MyDrive/fileGenerated.txt' # ruta y nombre a archivo a ESCRIBIR en su drive
f = open(ruta_arch, 'w') # abre archivo para escribir
texto = 'Esta es una linea de texto\nEsta es otra línea de text'
f.writelines(texto) # escribe contenido en archivo
f.close() # cierra archivo [texto del vínculo](https://)

## Repaso Python

####Ejercicio 1

Investigue/repase que son las listas, tuplas, conjuntos y diccionarios nativos de Python. Utilizando los constructores para cada tipo de dato genere
códigos de ejemplo y recórralos imprimiendo sus valores.

In [ ]:
print('Creo una lista , la recorro e imprimo todos sus elementos')
list1 = ['a','b','c','d']
##Para imprimirlos de una##
print(list1[0:4])
##Para recorrer la lista e imprimirl los elementos de a uno##
for element1 in list1:
   print(element1)

print('---------------------------------------------')
print('Creo una tupla e imprimo todos sus elementos')
tupla = ('a','z',1,2)
##Para imprimirlos de una##
print(tupla)
##Para recorrer la tupla e imprimir los elementos de a uno##
for element2 in tupla:
  print(element2)

print('---------------------------------------------')
print('Creo un set (conjunto) e imprimo todos sus elementos')
conjunto = {1,2,'f','g'}
#Para imprimir los elementos del set de una#
print(conjunto)
##Para recorrer el conjunto e imprimir los elementos de a uno##
for element3 in conjunto:
  print(element3)
print('---------------------------------------------')
print('Creo un diccionario (dict) e imprimo todos sus elementos')
figura_geometrica = {"tipo":"triangulo","area":5000,"color":"amarillo"}
print(figura_geometrica)
##Si quiero imprimir por elemento##
print(figura_geometrica["tipo"])

####Ejercicio 2

Genere el código necesario para recorrer simultáneamente 2 listas con la misma cantidad de elementos e imprima
los mismos utilizando un único for. (Usando función zip())

In [ ]:
list1 = [1,2,3,4]
list2 = [5,6,7,8]
combined = zip(list1,list2)
combined_list = list(combined)
print(combined_list)

[(1, 5), (2, 6), (3, 7), (4, 8)]


####Ejercicio 3


Implemente una función que a partir de la lista que recibe cómo parámetro, retorne una nueva lista sin elementos
repetidos. Compruebe su correcto funcionamiento.

In [ ]:
print('La lista con los elementos repetidos:')
lista = [1,1,2,3,4,5,6]
print(lista)
def eliminarDuplicados(input_list):
  listaNueva = list(set(lista))
  return listaNueva
print('La lista sin los elementos repetidos:')
print(eliminarDuplicados(lista))


La lista con los elementos repetidos:
[1, 1, 2, 3, 4, 5, 6]
La lista sin los elementos repetidos:
[1, 2, 3, 4, 5, 6]


Para la resolución de este ejercicio utilizamos la propiedad de los conjuntos (sets) : los elementos no se pueden repetir. Convertimos la lista en un set, se elimina automáticamente todos los elementos repetidos y "volvemos a convertir" a lista.

#### Ejercicio 4


Implemente una función que calcule la distancia entre 2 puntos (2D). Utilice la función sqrt del paquete math para
implementarla y compruebe el correcto funcionamiento de la misma

In [ ]:
import math
punto1={'x':10,'y':5}
punto2={'x':2,'y':4}
def distance(punto1,punto2):
    distance_points = math.sqrt(((punto2["x"]-punto1["x"])**2+(punto2["y"]-punto1["y"])**2))
    return distance_points
print("La distancia entre los dos puntos es: "+ str(distance(punto1,punto2)))

La distancia entre los dos puntos es: 8.06225774829855


#### Ejercicio 5

Investigue y escriba código que demuestre el funcionamiento de los “slices” en listas.

Las slices en listas en Python funcionan para extraer una porción deseada del contenido de una lista.
Por ejemplo, sea la siguiente lista definida como `lista_ejemplo` , vamos a extraer solo los elementos desde la posición 3 hasta la posición 7.

In [ ]:
lista_ejemplo=[1,2,3,4,5,6,7,8,9]
slice_lista_ejemplo=lista_ejemplo[2:6]
print(slice_lista_ejemplo)

[3, 4, 5, 6]


Supongamos que quiero tomar de una lista más grande, los elementos desde la posición 2 hasta la posición 14 pero de a "saltos" de 2 unidades. Entonces:

In [ ]:
lista_ejemplo=[1,2,3,4,5,6,7,8,9,10,11,12,13,14]
slice_lista_ejemplo=lista_ejemplo[1:13:2]
print(slice_lista_ejemplo)

[2, 4, 6, 8, 10, 12]


## Biblioteca Numpy

#### Ejercicio 1

Practique la creación de vectores, matrices y tensores

In [ ]:
#Creación de vector
import numpy as np
print('Imprimo un vector')
vector = np.array(['v','e','c','t','o','r'])
print(vector)
print('----------------------------')
#Creación de matriz
print('Imprimo una matriz de 6x2')
matriz = np.array([['m','a','t','r','i','z'],['z','i','r','t','a','m']])
print(matriz)
print('----------------------------')
#Creacion de tensores
print('Imprimo el tensor')
tens = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(tens)

Imprimo un vector
['v' 'e' 'c' 't' 'o' 'r']
----------------------------
Imprimo una matriz de 6x2
[['m' 'a' 't' 'r' 'i' 'z']
 ['z' 'i' 'r' 't' 'a' 'm']]
----------------------------
Imprimo el tensor
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Responda:

---

*   ¿Qué diferencias hay entre los constructores, array, empty, full, zeros, ones, identity?

    Dependiendo de con qué tipo de matriz vayamos a trabajar, vamos a utilizar distintos constructores que nos facilitarán el trabajo.
    Por ejemplo, si queremos trabajar con la matriz identidad, utilizamos la función identity.


*  array: crea una matriz con los elementos que le brindemos
*  empty: crea una matriz sin inicializar. Reserva memoria.
*  full: crea una matriz con todos elementos inicializados con un valor especificado.
*  zeros: crea una matriz cuyos elementos son ceros.
*  ones: crea una matriz inicializada en 1's
*  identity: crea una matriz identidad especificando la cantidad de filas deseadas.




---
    
*   ¿Qué tipos de datos pueden utilizarse? ¿En qué se diferencian? ¿Cuál es el tipo que se toma por defecto?¿Es siempre el mismo?

Los tipos de datos que pueden utilizarse en las anteriores funciones son:


*   int : valores numericos sin punto decimal
*   float: valores numéricos con punto decimal. Pueden representar numeros reales, racionales e irracionales.
*   complex: valores que cuentan con una parte real y otra imaginaria.

El tipo de dato que se toma por defecto es el **flotante**.

---
*   ¿Qué funciones se pueden utilizar para generar arreglos con números aleatorios?

Dentro de la libreria Numpy contamos con diferentes funciones de generación de números randoms y cada una con diferentes funcionalidades.
Entre ellas estan:


*   `numpy.random.randint()`: Genera números enteros aleatorios dentro de un rango específico.
*   `numpy.random.uniform()`: Genera números aleatorios con una distribución uniforme en un rango especificado.
*   `numpy.random.normal()`: Genera números aleatorios con una distribución normal, especificando la media y la desviación estándar
*   `numpy.random.seed()`:Permite establecer una semilla para la generación de números aleatorios, lo que hace que los resultados sean reproducibles.






#### Ejercicio 2


Investigue y ejemplifique las funciones relacionadas al tamaño de los arrays de Numpy

Las funciones que serán utilizadas en el ejemplo son:


1.   `numpy.shape()`: Devuelve la tupla de dimensiones de un array
2.   `numpy.ndim()` : Devuelve el número de dimensiones (el rango) de un array.
3.   `numpy.size()`: Devuelve el número total de elementos en un array.
4.   `numpy.reshape()`: Cambia la forma (dimensiones) de un array.
5.   `numpy.flatten()`: Se utiliza para convertir un array multidimensional en un array unidimensional
6.   `numpy.transpose()`: Devuelve la transposición de un array.
6. `numpy.len()`: Devuelve la cantidaad de elementos de una matriz. Se debe utilizar en matrices **unidimensionales**.



In [ ]:
import numpy as np
##Creamos una matriz de (4x4) para aplicarle todas las funciones##
matriz = np.array([[2,2,2,2],[4,4,4,4],[6,6,6,6],[8,8,8,8]])
print(matriz)
##--------------------------------------------------------------##
print('------------------')
print('Aplicamos .shape()')
print('La dimensión de la matriz es:'+str(np.shape(matriz)))
print('------------------')
print('Aplicamos .ndim()')
print('El rango de la matriz es:'+str(np.ndim(matriz)))
print('------------------')
print('Aplicamos .size()')
print('El total de elementos de la matriz es:'+str(np.size(matriz)))
print('------------------')
print('Aplicamos .flatten()')
matriz_uni = matriz.flatten()
print('Imprimimos la matriz unidimensional con los elementos de la anterior matriz:')
print(matriz_uni)
print('------------------')
print('Calculamos la transpuesta de la matriz')
np.transpose(matriz)

[[2 2 2 2]
 [4 4 4 4]
 [6 6 6 6]
 [8 8 8 8]]
------------------
Aplicamos .shape()
La dimensión de la matriz es:(4, 4)
------------------
Aplicamos .ndim()
El rango de la matriz es:2
------------------
Aplicamos .size()
El total de elementos de la matriz es:16
------------------
Aplicamos .flatten()
Imprimimos la matriz unidimensional con los elementos de la anterior matriz:
[2 2 2 2 4 4 4 4 6 6 6 6 8 8 8 8]
------------------
Calculamos la transpuesta de la matriz


array([[2, 4, 6, 8],
       [2, 4, 6, 8],
       [2, 4, 6, 8],
       [2, 4, 6, 8]])

#### Ejercicio 3

Practique funciones de agregación (sum, min, max, etc.) sobre vectores, matrices y tensores.


In [ ]:
import numpy as np
##Creo dos matrices##
matriz1 = np.array([[1,1,0],[3,3,3],[5,5,5]])
matriz2 = np.array([[2,2,0],[4,4,4],[6,6,6]])
print(matriz1)
print('-----------')
print(matriz2)
print('----------------------------------')
##------Funcion sum()------##
print('La suma de todos los elementos de cada matriz (por columnas)')
print('matriz1:'+str(sum(matriz1)))
print('matriz2:'+str(sum(matriz2)))
##------Funcion min()------##
print('----------------------------------')
print('Calculo del elemento de menor valor dentro de la matriz')
print('matriz1:'+str(np.min(matriz1)))
print('matriz2:'+str(np.min(matriz2)))
##------Funcion max()------##
print('----------------------------------')
print('Calculo del elemento de mayor valor dentro de la matriz')
print('matriz1:'+str(np.max(matriz1)))
print('matriz2:'+str(np.max(matriz2)))

[[1 1 0]
 [3 3 3]
 [5 5 5]]
-----------
[[2 2 0]
 [4 4 4]
 [6 6 6]]
----------------------------------
La suma de todos los elementos de cada matriz (por columnas)
matriz1:[9 9 8]
matriz2:[12 12 10]
----------------------------------
Calculo del elemento de menor valor dentro de la matriz
matriz1:0
matriz2:0
----------------------------------
Calculo del elemento de mayor valor dentro de la matriz
matriz1:5
matriz2:6


Estas funciones de agregación pueden aplicarse tanto a todos los elementos del array como a dimensiones específicas utilizando el argumento `axis`.

Ejemplo con tensores:

In [ ]:
tensor = np.array([[[1, 2],
                    [3, 4]],
                   [[5, 6],
                    [7, 8]]])

# Suma a lo largo de los ejes 1 y 2 (axis=(1, 2))
axis_sum = np.sum(tensor, axis=(1, 2))
print(axis_sum)

[10 26]


#### Ejercicio 4

Investigue y realice ejemplos que utilicen funciones para manipular elementos de arreglos (append, insert, delete,
etc.) y arreglos entre sí (vstack, hstack, contacenate, etc.)

Las siguientes funciones son utilizadas para **manipular elementos de arreglos**.

1.   `numpy.append()` :  Agrega elementos al final de un array.
2.   `numpy.insert()` :  Inserta elementos en una posición específica de un array.
3.   `numpy.delete()` : Elimina elementos de un array en una posición específica.


Ejemplos:


In [ ]:
import numpy as np
##Creación matriz##
print('Matriz original:')
matriz=np.array([[3,2,1],[1,1,1],[5,5,5]])
print(matriz)
##-----Uso funcion append----##
print('Agregamos una nueva columna con la función append dsp de la ultima columna de la matriz')
columna_extra = np.array([[100],[100],[100]])
append_matriz= np.append(matriz,columna_extra,axis=1)
print(append_matriz)
##-----Uso funcion insert----##
print('Agregamos una nueva fila con la función insert en la fila 0')
fila_extra = np.array([300,300,300])
insert_matriz = np.insert(matriz,0,fila_extra,axis=0)
print(insert_matriz)
##-----Uso funcion delete----##
print('Eliminamos la primera fila de la matriz')
delete = np.delete(matriz,0,axis=0)
print(delete)

Matriz original:
[[3 2 1]
 [1 1 1]
 [5 5 5]]
Agregamos una nueva columna con la función append dsp de la ultima columna de la matriz
[[  3   2   1 100]
 [  1   1   1 100]
 [  5   5   5 100]]
Agregamos una nueva fila con la función insert en la fila 0
[[300 300 300]
 [  3   2   1]
 [  1   1   1]
 [  5   5   5]]
Eliminamos la primera fila de la matriz
[[1 1 1]
 [5 5 5]]


Las siguientes funciones son utilizadas para **operaciones entre arreglos**.

1.   `numpy.vstack()` :  Apila verticalmente (concatena a lo largo del eje 0) dos o más arreglos.
2.   `numpy.hstack()` :  Apila horizontalmente (concatena a lo largo del eje 1) dos o más arreglos.
3.   `numpy.concatenate()` : Concatena arreglos a lo largo de un eje específico.

Ejemplos

In [ ]:
import numpy as np
##---------Uso del función vstack()---------##
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr1)
print('--------------')
arr2 = np.array([[7, 8, 9]])
print(arr2)
print('--------------')
stacked_arr = np.vstack((arr1, arr2))
print('Resultado con .vstack()')
print(stacked_arr)
print('------------------------------------------')
##---------Uso del función hstack()---------##
arr1 = np.array([1, 2, 3])
print(arr1)
print('--------------')
arr2 = np.array([4, 5, 6])
print(arr2)
print('--------------')
stacked_arr = np.hstack((arr1, arr2))
print('Resultado con .vstack()')
print(stacked_arr)
print('------------------------------------------')
##---------Uso del función concatenate()---------##
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])
concatenated_arr = np.concatenate((arr1, arr2), axis=0)
print(concatenated_arr)

[[1 2 3]
 [4 5 6]]
--------------
[[7 8 9]]
--------------
Resultado con .vstack()
[[1 2 3]
 [4 5 6]
 [7 8 9]]
------------------------------------------
[1 2 3]
--------------
[4 5 6]
--------------
Resultado con .vstack()
[1 2 3 4 5 6]
------------------------------------------
[[1 2]
 [3 4]
 [5 6]]


#### Ejercicio 5

Los arrays de numpy (así como las listas) proveen de un mecanismo versátil para hacer o referenciar una sección
de los mismos. Practique este mecanismo de acceso con vectores, matrices y tensores imprimiendo y
modificando distintas regiones de los mismos.

Ejemplos de acceso con matrices:

In [ ]:
import numpy as np
#Creo una matriz
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
# Acceder a un elemento específico
print("Elemento en la fila 1 y columna 2:", matrix[1, 2])
# Acceder a una fila completa
print("Fila 2:", matrix[1, :])
# Acceder a una columna completa
print("Columna 1:", matrix[:, 0])
# Modificar un elemento específico
matrix[0, 0] = 10
print("Matriz modificada:\n", matrix)

Elemento en la fila 1 y columna 2: 6
Fila 2: [4 5 6]
Columna 1: [1 4 7]
Matriz modificada:
 [[10  2  3]
 [ 4  5  6]
 [ 7  8  9]]


Ejemplos de acceso con tensores:




In [ ]:
import numpy as np

# Crear un tensor
tensor = np.array([[[1, 2],
                    [3, 4]],
                   [[5, 6],
                    [7, 8]]])

# Acceder a un elemento específico
print("Elemento en el tensor en la capa 1, fila 1 y columna 0:", tensor[0, 1, 0])

# Acceder a una capa completa
print("Capa 0:", tensor[0, :, :])

# Modificar un elemento específico
tensor[1, 1, 1] = 10
print("Tensor modificado:\n", tensor)


## Biblioteca Pandas

#### Ejercicio 1

In [ ]:
import pandas as pd

# Creaciom del diccionario
data = {
    'Nombre': ['Juan', 'Maria', 'Pedro', 'Jose'],
    'Edad': [20, 26, 18, 22],
    'Pais': ['Argentina', 'Peru', 'Brasil', 'Chile']
}

# Crear un DataFrame a partir del diccionario
df = pd.DataFrame(data)

# Mostrar el DataFrame
print(df)

print('------------------------------------------------------')
# Mostrar los nombres de las columnas
print('Nombre de las columnas:'+str(df.columns))




print('------------------------------------------------------')

# Sea la siguiente persona: Pablo | 30 años | Colombia

pabloData = pd.DataFrame({'Nombre': ['Pablo'], 'Edad': [30], 'Pais': ['Colombia']})

# Forma 1 para agregar la persona al Dataframe
# En esta forma, creamos otro Dataframe pero solamente con los campos pertenecientes a 'Pablo'
# Luego "unimos" dicho Dataframe 'pabloData' con el Dataframe original
df = pd.concat([df, pabloData], ignore_index=True)
df = pd.concat([df, pabloData], ignore_index=True)

print('Dataframe luego de agregar los datos:')
print(df)

print('------------------------------------------------------')

# Forma 1 para eliminar un dato
# Eliminando uno de los pablos utilizando iloc
df = df.iloc[:-1]


# Forma 2 para eliminar un dato
# Eliminando uno de los pablos utilizando drop()
# df.drop(df.index[-1], inplace=True)

print('Dataframe luego de eliminar los datos:')
print(df)

print('------------------------------------------------------')

#Para modificar el campo país que sea igual a Peru → Perú

df.loc[df['Pais'] == 'Peru', 'Pais'] = 'Perú'

print('Dataframe luego de modificar el campo Peru → Perd:')
print(df)

  Nombre  Edad       Pais
0   Juan    20  Argentina
1  Maria    26       Peru
2  Pedro    18     Brasil
3   Jose    22      Chile
------------------------------------------------------
Nombre de las columnas:Index(['Nombre', 'Edad', 'Pais'], dtype='object')
------------------------------------------------------
Dataframe luego de agregar los datos:
  Nombre  Edad       Pais
0   Juan    20  Argentina
1  Maria    26       Peru
2  Pedro    18     Brasil
3   Jose    22      Chile
4  Pablo    30   Colombia
5  Pablo    30   Colombia
------------------------------------------------------
Dataframe luego de eliminar los datos:
  Nombre  Edad       Pais
0   Juan    20  Argentina
1  Maria    26       Peru
2  Pedro    18     Brasil
3   Jose    22      Chile
4  Pablo    30   Colombia
------------------------------------------------------
Dataframe luego de modificar el campo Peru → Perd:
  Nombre  Edad       Pais
0   Juan    20  Argentina
1  Maria    26       Perú
2  Pedro    18     Brasil
3   Jos

#### Ejercicio 2

In [ ]:
import pandas as pd

# Creaciom del diccionario
data = {
    'Nombre': ['Juan', 'Maria', 'Pedro', 'Jose'],
    'Edad': [20, 26, 18, 22],
    'Pais': ['Argentina', 'Peru', 'Brasil', 'Chile']
}

# Crear un DataFrame a partir del diccionario
df = pd.DataFrame(data)


# Sea la siguiente persona: Pablo | 30 años | Colombia

pabloData = pd.DataFrame({'Nombre': ['Pablo'], 'Edad': [30], 'Pais': ['Colombia']})


# Mostrar el DataFrame
print(df)


# Guardar en archivo de texto con delimitador de tabulador
df.to_csv('archivo_delimitador_tab.txt', sep='\t', index=False)

# Guardar en archivo de texto con delimitador de punto y coma
df.to_csv('archivo_delimitador_punto_coma.csv', sep=';', index=False)

# Guardar en archivo Excel
df.to_excel('archivo_excel.xlsx', index=False)

# Guardar en archivo JSON
df.to_json('archivo_json.json', orient='records', indent=4)


  Nombre  Edad       Pais
0   Juan    20  Argentina
1  Maria    26       Peru
2  Pedro    18     Brasil
3   Jose    22      Chile
